server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

management:
  endpoints:
    web:
      exposure:
        include: metris, health, metrics

info:
  app: Spring Boot 2 Essentials By DevDojo
  website: https://devdojo.academy
  github: https://github.com/devdojobr/springboot-essentials